### ISSUE TITLE
On Ubuntu 18 with melodic, no catkin is available

### ISSUE THREAD

**Issue by Cirromulus** [pilsbot/workspace#1]
https://github.com/pilsbot/workspace/blob/8d475f0582ea9b4d7baf385b626240c6d93a57dd/tools/pb_build#L5

Instead catkin_make. Is this OS-Specific?

**Comment by DarthBubi** [comment]
You need to install `python-catkin-tools`.

**Comment by Cirromulus** [comment]
Maybe mention in howto?
